module Cosmo
  module API
    module Stats
      class Totals < Counters
        self.@instance: Totals

        def self.instance: () -> Totals

        def processed: () -> ::Integer

        def failed: () -> ::Integer
      end
    end
  end
end
