module Cosmo
  module API
    module Stats
      class Totals < Counter
        self.@instance: Totals

        def self.instance: () -> Totals

        def with: () { () -> bool } -> void

        def processed: () -> ::Integer

        def failed: () -> ::Integer
      end
    end
  end
end
