module Cosmo
  module Job
    class Data
      DEFAULTS: { stream: Symbol, retry: Integer, dead: bool, limit: nil }

      def self.default_retry: () -> Integer

      @class_name: ::String
      @args: Array[untyped]
      @options: Hash[Symbol, untyped]
      @at: Integer?
      @subject: ::String?

      attr_reader jid: ::String

      def initialize: (::String class_name, Array[untyped] args, ?Hash[Symbol, untyped]? options) -> void

      def stream: (?target: bool) -> Symbol

      def subject: () -> ::String

      def headers: () -> Hash[::String, untyped]

      def as_json: () -> { jid: ::String, class: ::String, args: Array[untyped], retry: Integer, dead: bool }

      def to_json: (*untyped _args) -> ::String?

      private

      def subject_for: (Symbol | ::String stream) -> ::String

      def validate!: () -> void

      def retries: () -> Integer

      def dead: () -> bool
    end
  end
end
