module Cosmo
  module Job
    module Enqueuer
      def self.enqueue: (::String class_name, Array[untyped] args, Hash[Symbol, untyped] options, ?batch: Batch?) -> ::String

      def self?.publish: (Data data) -> untyped
    end
  end
end
