module Cosmo
  module Job
    class Processor < ::Cosmo::Processor
      private

      def setup: () -> void

      def schedule_loop: () -> void

      def scheduler?: () -> bool

      def consumers: () -> Array[untyped]

      def fetch_subjects: (Hash[Symbol, untyped] config) -> untyped

      def fetch_timeout: (Hash[Symbol, untyped] config) -> Float

      def process: (Array[untyped] messages, untyped processor) -> void

      def handle_failure: (untyped message, Hash[Symbol, untyped] data) -> void

      def subscribe: (Symbol stream_name, Hash[Symbol, untyped] config) -> [untyped, Hash[Symbol, untyped], nil]

      def drop_message: (untyped message, Hash[Symbol, untyped] data) -> void

      def move_message: (untyped message, ?Hash[Symbol, untyped]? data) -> void

      def with_stats: (untyped message) { () -> untyped } -> void
    end
  end
end
