module Cosmo
  class Client
    self.@instance: Client
    @nc: untyped
    @js: untyped

    def self.instance: () -> Client

    attr_reader nc: untyped
    attr_reader js: untyped

    def initialize: (?nats_url: ::String) -> void

    def publish: (::String subject, ::String payload, **untyped params) -> untyped

    def subscribe: (::String | Array[::String] subject, ::String consumer_name, Hash[Symbol, untyped] config) -> untyped

    def stream_info: (::String | Symbol name) -> untyped

    def create_stream: (::String | Symbol name, Hash[Symbol, untyped] config) -> untyped

    def delete_stream: (::String | Symbol name, ?Hash[Symbol, untyped] params) -> untyped

    def list_streams: () -> Array[::String]

    def list_consumers: (::String stream_name) -> Array[Hash[::String, untyped]]

    def get_message: (::String | Symbol name, **untyped options) -> NATS::JetStream::API::RawStreamMsg

    def delete_message: (::String name, ::Integer seq) -> Hash[::String, untyped]

    def purge: (::String stream_name, ::String? subject) -> ::Integer?

    def consumer_info: (::String stream_name, ::String consumer_name) -> NATS::JetStream::API::ConsumerInfo

    def kv: (::String name, **untyped opts) -> NATS::KeyValue

    def close: -> void
  end
end
