module Cosmo
  class Config < ::Hash[Symbol, untyped]
    NANO: Integer
    DEFAULT_PATH: ::String

    self.@instance: Config
    self.@internal: Hash[Symbol, untyped]

    def self.instance: () -> Config

    def self.internal: () -> Hash[Symbol, untyped]

    def self.parse_file: (::String path) -> Hash[Symbol, untyped]

    def self.normalize!: (Hash[Symbol, untyped] config) -> void

    def self.deliver_policy: (Symbol | ::String | Time start_position) -> Hash[Symbol, ::String]

    def self.[]: (Symbol key) -> untyped

    def self.fetch: (Symbol key, ?untyped default) -> untyped

    def self.dig: (*Symbol keys) -> untyped

    def self.to_h: () -> Hash[Symbol, untyped]

    def self.set: (*untyped) -> untyped

    def self.load: (?::String? path) -> void


    def set: (*untyped) -> untyped

    def load: (?::String? path) -> void
  end
end
