module Cosmo
  class Config < ::Hash[Symbol, untyped]
    NANO: Integer
    DEFAULT_PATH: ::String
    DEFAULTS_FILE: ::String
    SERVICE_STREAMS: Array[Symbol]

    self.@instance: Config
    self.@internal: Hash[Symbol, untyped]

    def self.instance: () -> Config

    def self.internal: () -> Hash[Symbol, untyped]

    def self.to_ns: (Numeric seconds) -> ::Integer

    def self.read: (::String path) -> Hash[Symbol, untyped]

    def self.parse_file: (::String path) -> Hash[Symbol, untyped]

    def self.build: (Hash[Symbol, untyped] user) -> Hash[Symbol, untyped]

    def self.validate!: (Hash[Symbol, untyped] config) -> void

    def self.normalize!: (Hash[Symbol, untyped] config) -> void

    def self.deliver_policy: (Symbol | ::String | Time start_position) -> Hash[Symbol, ::String]

    def self.[]: (Symbol key) -> untyped

    def self.fetch: (Symbol key, ?untyped default) -> untyped

    def self.dig: (*Symbol keys) -> untyped

    def self.load: (?::String? path, ?overrides: Hash[Symbol, untyped]?) -> void

    def self.replicas: () -> Integer

    def self.scheduled: () -> Scheduled

    def self.dead: () -> Dead

    def self.batches: () -> Batches

    def self.server_middleware: () ?{ (Middleware::Chain chain) -> void } -> Middleware::Chain

    @server_middleware: Middleware::Chain

    def load: (?::String? path, ?overrides: Hash[Symbol, untyped]?) -> void

    def server_middleware: () ?{ (Middleware::Chain chain) -> void } -> Middleware::Chain

    @replicas: Integer?
    @scheduled: Scheduled
    @dead: Dead
    @batches: Batches

    attr_writer replicas: Integer

    def replicas: () -> Integer

    def scheduled: () -> Scheduled

    def dead: () -> Dead

    def batches: () -> Batches

    def logger: () -> untyped

    def logger=: (untyped logger) -> void

    def log_level=: (Symbol | ::String | Integer level) -> void
  end
end
