module Cosmo
  class Engine
    PROCESSORS: Hash[Symbol, Class]

    self.@instance: Engine
    @concurrency: Integer
    @pool: Utils::ThreadPool
    @running: untyped
    @quiet: untyped
    @processors: Array[Processor]
    @http_server: HTTPServer?
    @heartbeat: Heartbeat?

    def self.run: (*untyped) -> void

    def self.processors_for: ((::String | Symbol)? type) -> Array[Class]

    def self.instance: () -> Engine

    attr_reader concurrency: Integer

    def initialize: () -> void

    def run: (::String? type, Hash[Symbol, untyped] options) -> void

    def running?: () -> bool

    def state: () -> ::String

    def busy: () -> Integer

    def subscriptions: () -> Hash[Symbol, Array[::String]]

    def shutdown: () -> void

    private

    def start_http_server: () -> void

    def handle_shutdown: (Utils::Signal handler) -> Symbol

    def quiet: () -> void

    def unquiet: () -> void

    def drain_and_exit: (Utils::Signal handler) -> void

    def dump_threads: () -> void
  end
end
