module Cosmo
  class Engine
    PROCESSORS: Hash[Symbol, Class]

    self.@instance: Engine
    @concurrency: Integer
    @pool: Utils::ThreadPool
    @running: untyped
    @processors: Array[Processor]
    @http_server: HTTPServer?

    def self.run: (*untyped) -> void

    def self.instance: () -> Engine

    def initialize: () -> void

    def run: (::String? type, Hash[Symbol, untyped] options) -> void

    def running?: () -> bool

    def shutdown: () -> void

    private

    def start_http_server: () -> void
  end
end
