module Cosmo
  class Engine
    PROCESSORS: Hash[Symbol, Class]

    self.@instance: Engine
    @concurrency: Integer
    @pool: Utils::ThreadPool
    @running: untyped
    @quiet: untyped
    @processors: Array[Processor]

    def self.run: (*untyped) -> void

    def self.instance: () -> Engine

    def initialize: () -> void

    def run: (::String? type, Hash[Symbol, untyped] options) -> void

    def shutdown: () -> void

    private

    def handle_shutdown: (Utils::Signal handler) -> Symbol

    def quiet: () -> void

    def unquiet: () -> void

    def drain_and_exit: (Utils::Signal handler) -> void
  end
end
