module Cosmo
  module Job
    def self.included: (Class base) -> void

    module ClassMethods
      @default_options: Hash[Symbol, untyped]

      def options: (**untyped config) -> Hash[Symbol, untyped]
      alias cosmo_options options

      def concurrency_options: () -> { limit: Integer, key: Proc?, duration: Integer }?

      def concurrency_key: (Array[untyped] args) -> ::String?

      def limits_concurrency?: () -> bool

      def perform: (*untyped args, ?async: bool, **untyped options) -> (::String | nil)

      def perform_async: (*untyped args) -> ::String

      def perform_at: (Integer | Time timestamp, *untyped args) -> ::String

      def perform_in: (Integer | Float interval, *untyped args) -> ::String

      def perform_sync: (*untyped args) -> void

      def default_options: () -> Hash[Symbol, untyped]

      private

      def client: () -> Client
    end

    attr_accessor jid: ::String

    def perform: (*untyped) -> untyped

    def logger: () -> untyped
  end
end
