module Cosmo
  module Middleware
    class Limit
      def call: (untyped job, Hash[Symbol, untyped] data, untyped message) { () -> untyped } -> untyped

      private

      def acquire: (untyped job_class, Hash[Symbol, untyped] data) -> ::String?

      def timeout: (Numeric? duration) { () -> untyped } -> untyped
    end

    class Busy
      def call: (untyped job, Hash[Symbol, untyped] data, untyped message) { () -> untyped } -> untyped
    end

    class Totals
      def call: (untyped job, Hash[Symbol, untyped] data, untyped message) { () -> untyped } -> untyped

      private

      def increment: (Symbol key) -> void
    end
  end
end
