module Cosmo
  class Processor
    STREAM_PAUSED_RECHECK_TTL: Float
    STREAMS_PAUSED_IDLE_SLEEP: Float

    @pool: Utils::ThreadPool
    @running: untyped
    @consumers: Array[untyped]
    @threads: Array[Thread]
    @cache: Utils::TTLCache
    @options: Hash[Symbol, untyped]
    @locks: Hash[::String, Mutex]

    def self.run: (*untyped) -> Processor

    attr_reader consumers: Array[untyped]

    def initialize: (Utils::ThreadPool pool, untyped running, Hash[Symbol, untyped] options) -> void

    def run: () -> void

    def stop: (?::Integer | ::Float timeout) -> void

    private

    def run_loop: () -> void

    def work_loop: () -> void

    def schedule_loop: () -> void

    def scheduler?: () -> bool

    def setup: () -> void

    def process: (*untyped) -> void

    def fetch_timeout: (Hash[Symbol, untyped] config) -> Float

    def fetch_subjects: (Hash[Symbol, untyped] config) -> untyped

    def running?: () -> bool

    def fetch: (untyped subscription, batch_size: Integer, timeout: Float) ?{ (Array[untyped]) -> void } -> void

    def client: () -> Client

    def stopwatch: () -> Utils::Stopwatch

    def lock: (::String stream_name) { () -> void } -> void
  end
end
