module Cosmo
  class Publisher
    @client: Client

    def self.instance: () -> Publisher

    def self.publish: (::String subject, untyped data, ?serializer: Module?, **untyped options) -> untyped

    def initialize: () -> void

    def publish: (::String subject, untyped data, ?serializer: Module?, **untyped options) -> untyped
  end
end
