module Cosmo
  module API
    class KV
      @name: ::String
      @options: Hash[Symbol, untyped]
      @kv: untyped

      attr_reader kv: untyped

      def initialize: (::String name, ?Hash[Symbol, untyped]? options) -> void

      def set: (::String | ::Integer key, untyped value, ?ttl: ::Integer?) -> untyped

      def get: (::String | ::Integer key) -> untyped

      def delete: (::String | ::Integer key) -> untyped

      def keys: (?::String? subject, ?limit: ::Integer) -> Array[::String]

      def purge: (::String | ::Integer key) -> untyped

      def clean: () -> untyped

      def count: () -> ::Integer
      alias size count
    end
  end
end
