module Cosmo
  module Stream
    class Processor < ::Cosmo::Processor
      @configs: Array[Hash[Symbol, untyped]]

      def initialize: (Utils::ThreadPool pool, untyped running, Hash[Symbol, untyped] options) -> void

      private

      def run_loop: () -> void

      def setup: () -> void

      def work_loop: () -> void

      def process: (Array[untyped] messages, untyped processor) -> void

      def setup_configs: () -> void

      def setup_consumers: () -> void

      def static_config: -> Array[Hash[Symbol, untyped]]

      def dynamic_config: -> Array[Hash[Symbol, untyped]]
    end
  end
end
