module Cosmo
  module Stream
    class Processor < ::Cosmo::Processor
      @configs: Array[Hash[Symbol, untyped]]

      private

      def setup: () -> void

      def process: (Array[untyped] messages, untyped processor) -> void

      def fetch_subjects: (Hash[Symbol, untyped] config) -> untyped

      def fetch_timeout: (Hash[Symbol, untyped] config) -> Float

      def static_config: -> Array[Hash[Symbol, untyped]]

      def dynamic_config: -> Array[Hash[Symbol, untyped]]

      def subscribe: (Symbol? stream_name, Hash[Symbol, untyped] config) -> [untyped, Hash[Symbol, untyped], untyped]
    end
  end
end
