module Cosmo
  module Middleware
    class Sentry
      NAME_PREFIX: ::String
      OP_NAME: ::String
      SPAN_ORIGIN: ::String
      STATUS_OK: ::Integer
      STATUS_FAIL: ::Integer
      ERROR_HANDLER: ^(Exception error, Hash[Symbol, untyped] context) -> void

      def call: (untyped job, Hash[Symbol, untyped] data, untyped message) { () -> untyped } -> untyped
    end
  end
end
